# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5faddce5733125efb7ec4f497745dacb9a6dee327fd5e6fb981a952b2839861b2219c12f85a4eb5055b613438618829a73a05c31bdd004dc9ccfe04fa3f8635

test:
  secret_key_base: 7de0f4d08d5a494f46a885120d71cc7e30f487a889656ababfe6bdcd5b7cdc8b230c73a6dcbb58c4770223c5742efe2ff108fb63b5507af89d3c7c01675902d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
